### ISSUE TITLE
Wrong Config.cfg location

### ISSUE THREAD

**Issue by ducakar** [linuxgurugamer/EvaFollower#2]
The default config file is packaged at GameData/EvaFollower/PluginData/EvaFollower/Config.cfg but should be GameData/EvaFollower/**Plugins**/PluginData/EvaFollower/Config.cfg to be found by the plugin.

**Comment by linuxgurugamer** [comment]
It may be in the wrong location, but don't tell me where it should be.  All my mods put the config files into the MODDIR/PluginData directory, I don't put them into the Plugins/PluginData ..... directory.

I'll get the file updated today

Edit:  Looks like I never updated this one, so I'll have to update the mod to fix this.

**Comment by linuxgurugamer** [comment]
I'm sorry, I was too harsh.  I've had a lot of people telling me what to do with my mods recently, and I shouldn't have snapped at you.

For now, move the file to where you said, but I'll be updating this soon to put it in my standard location

**Comment by linuxgurugamer** [comment]
fixed in latest release
