### ISSUE TITLE
1.5.x: Female on EVA cannot remove helmets

### ISSUE THREAD

**Issue by jh4c** [linuxgurugamer/EvaFollower#4]
This is an issue that has arisen when updating from 1.4.x to 1.5.x: with the arrival of new models of flight suit, the Remove Helmet option no longer works on Female Kerbals when on EVA. All other mod-added controls in the action menu continue to work as expected.

**Comment by linuxgurugamer** [comment]
Just tested in 1.5.1.  Make sure you enable the Remove Helmut option in the new Settings page
