### ISSUE TITLE
Wrong download on SpaceDock

### ISSUE THREAD

**Issue by HebaruSan** [linuxgurugamer/EvaFollower#6]
This seems to be a different mod starting with "EVA"...

https://spacedock.info/mod/1582/EvaFollower/download/0.2.0.2

![image](https://user-images.githubusercontent.com/1559108/67637694-0811ef80-f8ab-11e9-8a14-425ff7647923.png)

**Comment by HebaruSan** [comment]
Tagging @linuxgurugamer to ensure notification

**Comment by linuxgurugamer** [comment]
Hmm, I'll have to do bump the version, will do it this evening

**Comment by HebaruSan** [comment]
Got fixed.

https://github.com/KSP-CKAN/CKAN-meta/blob/master/EvaFollower/EvaFollower-1-1.1.1.3.ckan
